const Menu = [
  {
    id: 1,
    image: "images/maggi.jpg",
    name: "maggi",
    category: "breakfast",
    price: "12₹",
    description: "Delicious instant noodles that are perfect for breakfast or anytime snack. Made with a savory broth and accompanied by a flavorful seasoning, Maggi noodles offer a satisfying and comforting meal. Whether you're craving a warm bowl of noodles or need a quick bite during the day, Maggi is sure to satisfy your taste buds.",
  },
  {
    id: 2,
    image: "images/allupakoida.jpg",
    name: "Crispy",
    category: "evening",
    price: "20₹",
    description: "Crispy and flavorful potato fritters, a popular evening snack option. Made by dipping slices of potatoes in a gram flour batter and deep-frying them to golden perfection. Allu pakoida is often enjoyed with a cup of hot tea or served as an appetizer at social gatherings.",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "breakfast",
    price: "10₹",
    description: "Fresh and juicy corn kernels, a healthy and tasty breakfast choice. Whether added to salads, used as a topping for pizzas, or simply boiled and seasoned with butter and salt, corn adds a burst of sweetness and crunch to any dish. Packed with fiber and essential nutrients, corn is a nutritious option to start your day.",
  },
  {
    id: 4,
    image: "../images/chola.jpg",
    name: "chola",
    category: "lunch",
    price: "50₹",
    description: "A spicy and tangy chickpea curry, perfect for a fulfilling lunch. Chola, also known as chana masala, is a popular North Indian dish made with tender chickpeas cooked in a flavorful blend of spices, tomatoes, and onions. This aromatic curry is rich in protein and pairs well with rice or naan bread.",
  },
  {
    id: 5,
    image: "../images/pizza.jpg",
    name: "pizza",
    category: "evening",
    price: "80₹",
    description: "Delicious pizza with a variety of toppings, a popular choice for evening cravings. Whether you prefer a traditional Margherita or like to explore gourmet combinations, there's a pizza for everyone's taste. Satisfy your evening cravings with a hot and delicious pizza that will leave you wanting more.",
  },
  {
    id: 6,
    image: "../images/nonvegthali.jpg",
    name: "Thali",
    category: "dinner",
    price: "180₹",
    description: "A wholesome dinner option with a variety of non-vegetarian dishes. The Non-Veg Thali is a complete meal that typically includes a selection of meat or fish dishes, along with rice, bread, lentils, vegetables, and a range of flavorful accompaniments. Indulge in the spicy and flavorful non-vegetarian delicacies for a satisfying and wholesome dining experience.",
  },
  {
    id: 7,
    image: "../images/sweet.jpg",
    name: "Sweets",
    category: "dinner",
    price: "60₹",
    description: "Indulge in a variety of delectable sweets for a delightful dinner finale. From traditional delights like gulab jamun and jalebi to regional specialties like rasgulla and peda, there is a wide assortment of sweets to choose from. Treat yourself to a selection of mouthwatering sweets and satisfy your sweet tooth cravings.",
  },
  {
    id: 8,
    image: "../images/rajmarice.jpg",
    name: "Hearty",
    category: "lunch",
    price: "60₹",
    description: "A classic combination of kidney bean curry and rice, a fulfilling lunch option. Rajma rice is a popular North Indian dish that brings together tender kidney beans cooked in a flavorful gravy, served alongside steamed rice. The combination of spices and the creamy texture of rajma create a satisfying and balanced lunchtime feast.",
  },
  {
    id: 9,
    image: "../images/samosa.jpg",
    name: "samosa",
    category: "evening",
    price: "10₹",
    description: "Crispy and savory pastry filled with spicy potato filling, a popular evening snack. Samosa is a beloved Indian snack that consists of a crispy triangular pastry filled with a delicious mixture of spiced potatoes, peas, and aromatic herbs. Whether you're grabbing a quick bite on the go or serving it as an appetizer at a gathering, samosas are sure to delight your taste buds.",
  },
];

export default Menu;